export const sampleLifeStyleData = {
  admissionYear: '20',
  numOfRoommate: 4,
  dormitoryName: '제 1생활관',
  acceptance: '합격',
  wakeUpMeridian: '오전',
  wakeUpTime: 7,
  sleepingMeridian: '오후',
  sleepingTime: 11,
  turnOffMeridian: '오후',
  turnOffTime: 10,
  smoking: '비흡연자',
  sleepingHabit: ['잠버릇이 없어요'],
  airConditioningIntensity: 2,
  heatingIntensity: 1,
  lifePattern: '아침형 인간',
  intimacy: '필요한 말만 했으면 좋겠어요',
  canShare: '휴지정도는 빌려줄 수 있어요',
  isPlayGame: '아예 하지 않아요',
  isPhoneCall: '급한 전화만 해요',
  studying: '시험기간 때만 해요',
  intake: '음료만 마셔요',
  cleanSensitivity: 3,
  noiseSensitivity: 3,
  cleaningFrequency: '일주일에 한 번 해요',
  drinkingFrequency: '일주일에 한 두번 마셔요',
  personality: ['활발해요', '집이 좋아요'],
  mbti: 'INFP',
};
