export const sampleLifeStyleData = {
  admissionYear: '20',
  numOfRoommate: 4,
  dormName: '제 1생활관',
  dormJoiningStatus: '합격',
  wakeUpTime: 7,
  sleepingTime: 11,
  turnOffTime: 10,
  smokingStatus: '비흡연자',
  sleepingHabits: ['잠버릇이 없어요'],
  coolingIntensity: '적당하게 틀어요',
  heatingIntensity: '약하게 틀어요',
  lifePattern: '아침형 인간',
  intimacy: '필요한 말만 했으면 좋겠어요',
  sharingStatus: '휴지정도는 빌려줄 수 있어요',
  gamingStatus: '아예 하지 않아요',
  callingStatus: '급한 전화만 해요',
  studyingStatus: '시험기간 때만 해요',
  eatingStatus: '음료만 마셔요',
  cleannessSensitivity: '보통이에요',
  noiseSensitivity: '보통이에요',
  cleaningFrequency: '일주일에 한 번 해요',
  drinkingFrequency: '일주일에 한 두번 마셔요',
  personalities: ['활발해요', '집이 좋아요'],
  mbti: 'INFP',
};
