export enum EventCategory {
  Cozyhome = 'cozyhome',
  Lifestyle = 'lifestyle',
  Onboarding = 'onboarding',
  RoomRecommendation = 'room_recommendation',
  RoommateRecommendation = 'roommate_recommendation',
}

export enum ButtonEvent {
  agree_1 = 'agree_1',
  agree_2 = 'agree_2',
  agree_all = 'agree_all',
  chat = 'chat',
  notice = 'notice',
  life_style = 'life_style',
  make_room = 'make_room',
  join_room = 'join_room',
  verify_email = 'verify_email',
  nav_bar = 'nav_bar',
  okay = 'okay',
  name = 'name',
  mate_more = 'mate_more',
  mate_component = 'mate_component',
  room_more = 'room_more',
  room_component = 'room_component',
  my_room = 'my_room',
  request_component = 'request_component',
  request_more = 'request_more',
  univ = 'univ',
  major = 'major',
  email = 'email',
  email_code = 'email_code',
  room_card = 'room_card',
  // 라이프스타일 value
  birthYear = 'birthYear',
  admissionYear = 'admissionYear',
  majorName = 'majorName',
  dormJoiningStatus = 'dormJoiningStatus',
  wakeUpTime = 'wakeUpTime',
  sleepingTime = 'sleepingTime',
  turnOffTime = 'turnOffTime',
  smokingStatus = 'smokingStatus',
  sleepingHabits = 'sleepingHabits',
  coolingIntensity = 'coolingIntensity',
  heatingIntensity = 'heatingIntensity',
  lifePattern = 'lifePattern',
  intimacy = 'intimacy',
  sharingStatus = 'sharingStatus',
  gamingStatus = 'gamingStatus',
  callingStatus = 'callingStatus',
  studyingStatus = 'studyingStatus',
  eatingStatus = 'eatingStatus',
  cleannessSensitivity = 'cleannessSensitivity',
  noiseSensitivity = 'noiseSensitivity',
  cleaningFrequency = 'cleaningFrequency',
  drinkingFrequency = 'drinkingFrequency',
  personalities = 'personalities',
  mbti = 'mbti',
}

export enum InputEvent {
  Birth = 'birth',
  Email = 'email',
  Email_code = 'email_code',
  Gender = 'gender',
  Major = 'major',
  Name = 'name',
  Univ = 'univ',
}

export enum ScreenName {
  Onboarding = 'onboarding',
  RoomRecommendation = 'room_recommendation',
  RoommateRecommendation = 'roommate_recommendation',
}
