export enum EventCategory {
  Cozyhome = 'cozyhome',
  Lifestyle = 'lifestyle',
  Onboarding = 'onboarding',
  RoomRecommendation = 'room_recommendation',
  RoommateRecommendation = 'roommate_recommendation',
}

export enum ButtonEvent {
  Agree_1 = 'agree_1',
  Agree_2 = 'agree_2',
  Agree_all = 'agree_all',
  Aircon = 'aircon',
  Birth = 'birth',
  Clean_freq = 'clean_freq',
  Clean_sensitivity = 'clean_sensitivity',
  Closeness = 'closeness',
  Dorm_pass = 'dorm_pass',
  Drink = 'drink',
  Drinking_freq = 'drinking_freq',
  Eat = 'eat',
  Email = 'email',
  Email_code = 'email_code',
  Game = 'game',
  Heater = 'heater',
  Item_sharing = 'item_sharing',
  Join_room = 'join_room',
  Light_off = 'light_off',
  Lifestyle = 'lifestyle',
  Mbti = 'mbti',
  Major = 'major',
  Morning = 'morning',
  Name = 'name',
  Nav_bar = 'nav_bar',
  Night = 'night',
  Okay = 'okay',
  Personality = 'personality',
  Phone_call = 'phone_call',
  Room_card = 'room_card',
  Smoke = 'smoke',
  Sleep_habit = 'sleep_habit',
  Student_id = 'student_id',
  Study = 'study',
  Univ = 'univ',
  Verify_email = 'verify_email',
}

export enum InputEvent {
  Birth = 'birth',
  Email = 'email',
  Email_code = 'email_code',
  Gender = 'gender',
  Major = 'major',
  Name = 'name',
  Univ = 'univ',
}

export enum ScreenName {
  Onboarding = 'onboarding',
  RoomRecommendation = 'room_recommendation',
  RoommateRecommendation = 'roommate_recommendation',
}
