export type ActionType =
  | 'SELECT_COZY_MATE'
  | 'COMPLETE_ALL_TODAY_TODO'
  | 'REMINDER_ROLE'
  | 'TODO_LIST'
  | 'ROOM_IN'
  | 'ROOM_OUT'
  | 'ACCEPT_ROOM_INVITE'
  | 'ARRIVE_ROOM_INVITE'
  | 'ACCEPT_ROOM_JOIN'
  | 'ARRIVE_ROOM_JOIN_REQUEST';