export type MemberStatItem = {
  dormName: string;
  numOfRoommate: string;
  admissionYear: string;
  dormJoiningStatus: string;
  wakeUpTime: number | undefined;
  sleepingTime: number | undefined;
  turnOffTime: number | undefined;
  smokingStatus: string;
  sleepingHabits: string[];
  coolingIntensity: string;
  heatingIntensity: string;
  lifePattern: string;
  intimacy: string;
  sharingStatus: string;
  gamingStatus: string;
  callingStatus: string;
  studyingStatus: string;
  eatingStatus: string;
  cleannessSensitivity: string;
  noiseSensitivity: string;
  cleaningFrequency: string;
  drinkingFrequency: string;
  personalities: string[];
  mbti: string;
  selfIntroduction: string;
};
