export interface ListViewProps {
  // userBasicData: {
  //   memberId: number;
  //   memberName: string;
  //   memberNickName: string;
  //   memberAge: number;
  //   memberPersona: number;
  //   numOfRoommate: number;
  //   equality: number;
  // };
  userData: {
    universityId: number;
    admissionYear: string;
    birthYear?: number;
    major: string;
    numOfRoommate: number | undefined;
    acceptance: string;
    wakeUpMeridian: string;
    wakeUpTime: number | undefined;
    sleepingMeridian: string;
    sleepingTime: number | undefined;
    turnOffMeridian: string;
    turnOffTime: number | undefined;
    smokingState: string;
    sleepingHabit: string[];
    airConditioningIntensity: number | undefined;
    heatingIntensity: number | undefined;
    lifePattern: string;
    intimacy: string;
    canShare: string;
    isPlayGame: string;
    isPhoneCall: string;
    studying: string;
    intake: string;
    cleanSensitivity: number | undefined;
    noiseSensitivity: number | undefined;
    cleaningFrequency: string;
    drinkingFrequency: string;
    personality: string[];
    mbti: string;
    selfIntroduction: string;
  };
}

export interface TableViewProps {
  userData: {
    universityId: number;
    admissionYear: string;
    birthYear?: number;
    major: string;
    numOfRoommate: number;
    acceptance: string;
    wakeUpMeridian: string;
    wakeUpTime: number;
    sleepingMeridian: string;
    sleepingTime: number;
    turnOffMeridian: string;
    turnOffTime: number;
    smokingState: string;
    sleepingHabit: string[];
    airConditioningIntensity: number;
    heatingIntensity: number;
    lifePattern: string;
    intimacy: string;
    canShare: string;
    isPlayGame: string;
    isPhoneCall: string;
    studying: string;
    intake: string;
    cleanSensitivity: number;
    noiseSensitivity: number;
    cleaningFrequency: string;
    drinkingFrequency: string;
    personality: string[];
    mbti: string;
    selfIntroduction: string;
  };
  otherUserData: {
    universityId: number;
    admissionYear: string;
    birthYear?: number;
    major: string;
    numOfRoommate: number | undefined;
    acceptance: string;
    wakeUpMeridian: string;
    wakeUpTime: number | undefined;
    sleepingMeridian: string;
    sleepingTime: number | undefined;
    turnOffMeridian: string;
    turnOffTime: number | undefined;
    smokingState: string;
    sleepingHabit: string[];
    airConditioningIntensity: number;
    heatingIntensity: number;
    lifePattern: string;
    intimacy: string;
    canShare: string;
    isPlayGame: string;
    isPhoneCall: string;
    studying: string;
    intake: string;
    cleanSensitivity: number;
    noiseSensitivity: number;
    cleaningFrequency: string;
    drinkingFrequency: string;
    personality: string[];
    mbti: string;
    selfIntroduction: string;
  };
}
